package neton.http.h1.parse

// GENERATED from httparse 1.10.1 `tests/uri.rs` (263 `req!` cases, `urltest_001` .. `urltest_262` and `urltest_nvidia`); do not edit by hand.
// Each case keeps the reference input and expectations verbatim. Every case expects `Complete(input.length)`
// unless it names an error. Rust byte-string escapes (\r \n \\ \") read the same in Kotlin string literals.

internal class UriCase(
    val name: String,
    val input: String,
    val error: HttpParseError? = null,
    val method: String? = null,
    val path: String? = null,
    val version: Int = -1,
    val headers: List<Pair<String, String>> = emptyList(),
)

internal val URI_CASES: List<UriCase> = listOf(
    UriCase(
        "urltest_001",
        "GET /bar;par?b HTTP/1.1\r\nHost: foo\r\n\r\n",
        method = "GET", path = "/bar;par?b", version = 1,
        headers = listOf("Host" to "foo"),
    ),
    UriCase(
        "urltest_002",
        "GET /x HTTP/1.1\r\nHost: test\r\n\r\n",
        method = "GET", path = "/x", version = 1,
        headers = listOf("Host" to "test"),
    ),
    UriCase(
        "urltest_003",
        "GET /x HTTP/1.1\r\nHost: test\r\n\r\n",
        method = "GET", path = "/x", version = 1,
        headers = listOf("Host" to "test"),
    ),
    UriCase(
        "urltest_004",
        "GET /foo/foo.com HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/foo.com", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_005",
        "GET /foo/:foo.com HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:foo.com", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_006",
        "GET /foo/foo.com HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/foo.com", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase("urltest_007", "GET  foo.com HTTP/1.1\r\nHost: \r\n\r\n", error = HttpParseError.Token),
    UriCase(
        "urltest_008",
        "GET /%20b%20?%20d%20 HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/%20b%20?%20d%20", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase("urltest_009", "GET x x HTTP/1.1\r\nHost: \r\n\r\n", error = HttpParseError.Version),
    UriCase(
        "urltest_010",
        "GET /c HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/c", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase(
        "urltest_011",
        "GET /c HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/c", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase(
        "urltest_012",
        "GET /c HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/c", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase(
        "urltest_013",
        "GET /c HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/c", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase(
        "urltest_014",
        "GET /c HTTP/1.1\r\nHost: f\r\n\r\n",
        method = "GET", path = "/c", version = 1,
        headers = listOf("Host" to "f"),
    ),
    UriCase(
        "urltest_015",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_016",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_017",
        "GET /foo/:foo.com/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:foo.com/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_018",
        "GET /foo/:foo.com/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:foo.com/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_019",
        "GET /foo/: HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_020",
        "GET /foo/:a HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:a", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_021",
        "GET /foo/:/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_022",
        "GET /foo/:/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_023",
        "GET /foo/: HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_024",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_025",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_026",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_027",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_028",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_029",
        "GET /foo/:23 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:23", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_030",
        "GET /:23 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/:23", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_031",
        "GET /foo/:: HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/::", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_032",
        "GET /foo/::23 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/::23", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_033",
        "GET /d HTTP/1.1\r\nHost: c\r\n\r\n",
        method = "GET", path = "/d", version = 1,
        headers = listOf("Host" to "c"),
    ),
    UriCase(
        "urltest_034",
        "GET /foo/:@c:29 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/:@c:29", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_035",
        "GET //@ HTTP/1.1\r\nHost: foo.com\r\n\r\n",
        method = "GET", path = "//@", version = 1,
        headers = listOf("Host" to "foo.com"),
    ),
    UriCase(
        "urltest_036",
        "GET /b:c/d@foo.com/ HTTP/1.1\r\nHost: a\r\n\r\n",
        method = "GET", path = "/b:c/d@foo.com/", version = 1,
        headers = listOf("Host" to "a"),
    ),
    UriCase(
        "urltest_037",
        "GET /bar.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/bar.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_038",
        "GET /////// HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "///////", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_039",
        "GET ///////bar.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "///////bar.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_040",
        "GET //:///// HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "//://///", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_041",
        "GET /foo HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/foo", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_042",
        "GET /bar HTTP/1.1\r\nHost: foo\r\n\r\n",
        method = "GET", path = "/bar", version = 1,
        headers = listOf("Host" to "foo"),
    ),
    UriCase(
        "urltest_043",
        "GET /path;a??e HTTP/1.1\r\nHost: foo\r\n\r\n",
        method = "GET", path = "/path;a??e", version = 1,
        headers = listOf("Host" to "foo"),
    ),
    UriCase(
        "urltest_044",
        "GET /abcd?efgh?ijkl HTTP/1.1\r\nHost: foo\r\n\r\n",
        method = "GET", path = "/abcd?efgh?ijkl", version = 1,
        headers = listOf("Host" to "foo"),
    ),
    UriCase(
        "urltest_045",
        "GET /abcd HTTP/1.1\r\nHost: foo\r\n\r\n",
        method = "GET", path = "/abcd", version = 1,
        headers = listOf("Host" to "foo"),
    ),
    UriCase(
        "urltest_046",
        "GET /foo/[61:24:74]:98 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/[61:24:74]:98", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_047",
        "GET /foo/[61:27]/:foo HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/[61:27]/:foo", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_048",
        "GET /example.com/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_049",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_050",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_051",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_052",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_053",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_054",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_055",
        "GET /foo/example.com/ HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/example.com/", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_056",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_057",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_058",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_059",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_060",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_061",
        "GET /a/b/c HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/a/b/c", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_062",
        "GET /a/%20/c HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/a/%20/c", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_063",
        "GET /a%2fc HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/a%2fc", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_064",
        "GET /a/%2f/c HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/a/%2f/c", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_065",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_066",
        "GET text/html,test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "text/html,test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_067",
        "GET 1234567890 HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "1234567890", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_068",
        "GET /c:/foo/bar.html HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:/foo/bar.html", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_069",
        "GET /c:////foo/bar.html HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:////foo/bar.html", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_070",
        "GET /C:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_071",
        "GET /C:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_072",
        "GET /C:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_073",
        "GET /file HTTP/1.1\r\nHost: server\r\n\r\n",
        method = "GET", path = "/file", version = 1,
        headers = listOf("Host" to "server"),
    ),
    UriCase(
        "urltest_074",
        "GET /file HTTP/1.1\r\nHost: server\r\n\r\n",
        method = "GET", path = "/file", version = 1,
        headers = listOf("Host" to "server"),
    ),
    UriCase(
        "urltest_075",
        "GET /file HTTP/1.1\r\nHost: server\r\n\r\n",
        method = "GET", path = "/file", version = 1,
        headers = listOf("Host" to "server"),
    ),
    UriCase(
        "urltest_076",
        "GET /foo/bar.txt HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/foo/bar.txt", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_077",
        "GET /home/me HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/home/me", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_078",
        "GET /test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_079",
        "GET /test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_080",
        "GET /tmp/mock/test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/tmp/mock/test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_081",
        "GET /tmp/mock/test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/tmp/mock/test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_082",
        "GET /foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_083",
        "GET /.foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/.foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_084",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_085",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_086",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_087",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_088",
        "GET /foo/..bar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/..bar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_089",
        "GET /foo/ton HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/ton", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_090",
        "GET /a HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/a", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_091",
        "GET /ton HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/ton", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_092",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_093",
        "GET /foo/%2e%2 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/%2e%2", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_094",
        "GET /%2e.bar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%2e.bar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_095",
        "GET // HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "//", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_096",
        "GET /foo/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_097",
        "GET /foo/bar/ HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo/bar/", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_098",
        "GET /foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_099",
        "GET /%20foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%20foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_100",
        "GET /foo% HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_101",
        "GET /foo%2 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%2", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_102",
        "GET /foo%2zbar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%2zbar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_103",
        "GET /foo%2%C3%82%C2%A9zbar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%2%C3%82%C2%A9zbar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_104",
        "GET /foo%41%7a HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%41%7a", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_105",
        "GET /foo%C2%91%91 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%C2%91%91", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_106",
        "GET /foo%00%51 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foo%00%51", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_107",
        "GET /(%28:%3A%29) HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/(%28:%3A%29)", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_108",
        "GET /%3A%3a%3C%3c HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%3A%3a%3C%3c", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_109",
        "GET /foobar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/foobar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_110",
        "GET //foo//bar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "//foo//bar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_111",
        "GET /%7Ffp3%3Eju%3Dduvgw%3Dd HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%7Ffp3%3Eju%3Dduvgw%3Dd", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_112",
        "GET /@asdf%40 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/@asdf%40", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_113",
        "GET /%E4%BD%A0%E5%A5%BD%E4%BD%A0%E5%A5%BD HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%E4%BD%A0%E5%A5%BD%E4%BD%A0%E5%A5%BD", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_114",
        "GET /%E2%80%A5/foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%E2%80%A5/foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_115",
        "GET /%EF%BB%BF/foo HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%EF%BB%BF/foo", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_116",
        "GET /%E2%80%AE/foo/%E2%80%AD/bar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/%E2%80%AE/foo/%E2%80%AD/bar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_117",
        "GET /foo?bar=baz HTTP/1.1\r\nHost: www.google.com\r\n\r\n",
        method = "GET", path = "/foo?bar=baz", version = 1,
        headers = listOf("Host" to "www.google.com"),
    ),
    UriCase(
        "urltest_118",
        "GET /foo?bar=baz HTTP/1.1\r\nHost: www.google.com\r\n\r\n",
        method = "GET", path = "/foo?bar=baz", version = 1,
        headers = listOf("Host" to "www.google.com"),
    ),
    UriCase(
        "urltest_119",
        "GET test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_120",
        "GET /foo%2Ehtml HTTP/1.1\r\nHost: www\r\n\r\n",
        method = "GET", path = "/foo%2Ehtml", version = 1,
        headers = listOf("Host" to "www"),
    ),
    UriCase(
        "urltest_121",
        "GET /foo/html HTTP/1.1\r\nHost: www\r\n\r\n",
        method = "GET", path = "/foo/html", version = 1,
        headers = listOf("Host" to "www"),
    ),
    UriCase(
        "urltest_122",
        "GET /foo HTTP/1.1\r\nHost: www.google.com\r\n\r\n",
        method = "GET", path = "/foo", version = 1,
        headers = listOf("Host" to "www.google.com"),
    ),
    UriCase(
        "urltest_123",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_124",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_125",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_126",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_127",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_128",
        "GET /example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_129",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_130",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_131",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_132",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_133",
        "GET example.com/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "example.com/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_134",
        "GET /test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_135",
        "GET /test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_136",
        "GET /test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_137",
        "GET /test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_138",
        "GET /aaa/test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/aaa/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_139",
        "GET /test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_140",
        "GET /%E4%B8%AD/test.txt HTTP/1.1\r\nHost: www.example.com\r\n\r\n",
        method = "GET", path = "/%E4%B8%AD/test.txt", version = 1,
        headers = listOf("Host" to "www.example.com"),
    ),
    UriCase(
        "urltest_141",
        "GET /... HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/...", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_142",
        "GET /a HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/a", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_143",
        "GET /%EF%BF%BD?%EF%BF%BD HTTP/1.1\r\nHost: x\r\n\r\n",
        method = "GET", path = "/%EF%BF%BD?%EF%BF%BD", version = 1,
        headers = listOf("Host" to "x"),
    ),
    UriCase(
        "urltest_144",
        "GET /bar HTTP/1.1\r\nHost: example.com\r\n\r\n",
        method = "GET", path = "/bar", version = 1,
        headers = listOf("Host" to "example.com"),
    ),
    UriCase(
        "urltest_145",
        "GET test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_146",
        "GET x@x.com HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "x@x.com", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_147",
        "GET , HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = ",", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_148",
        "GET blank HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "blank", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_149",
        "GET test?test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "test?test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_150",
        "GET /%60%7B%7D?`{} HTTP/1.1\r\nHost: h\r\n\r\n",
        method = "GET", path = "/%60%7B%7D?`{}", version = 1,
        headers = listOf("Host" to "h"),
    ),
    UriCase(
        "urltest_151",
        "GET /?%27 HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/?%27", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_152",
        "GET /?' HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/?'", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_153",
        "GET /some/path HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/some/path", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_154",
        "GET /smth HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/smth", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_155",
        "GET /some/path HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/some/path", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_156",
        "GET /pa/i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_157",
        "GET /i HTTP/1.1\r\nHost: ho\r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to "ho"),
    ),
    UriCase(
        "urltest_158",
        "GET /pa/i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_159",
        "GET /i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_160",
        "GET /i HTTP/1.1\r\nHost: ho\r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to "ho"),
    ),
    UriCase(
        "urltest_161",
        "GET /i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_162",
        "GET /i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_163",
        "GET /i HTTP/1.1\r\nHost: ho\r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to "ho"),
    ),
    UriCase(
        "urltest_164",
        "GET /i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_165",
        "GET /pa/pa?i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/pa?i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_166",
        "GET /pa?i HTTP/1.1\r\nHost: ho\r\n\r\n",
        method = "GET", path = "/pa?i", version = 1,
        headers = listOf("Host" to "ho"),
    ),
    UriCase(
        "urltest_167",
        "GET /pa/pa?i HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/pa?i", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_168",
        "GET sd HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "sd", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_169",
        "GET sd/sd HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "sd/sd", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_170",
        "GET /pa/pa HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/pa", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_171",
        "GET /pa HTTP/1.1\r\nHost: ho\r\n\r\n",
        method = "GET", path = "/pa", version = 1,
        headers = listOf("Host" to "ho"),
    ),
    UriCase(
        "urltest_172",
        "GET /pa/pa HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pa/pa", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_173",
        "GET /x HTTP/1.1\r\nHost: %C3%B1\r\n\r\n",
        method = "GET", path = "/x", version = 1,
        headers = listOf("Host" to "%C3%B1"),
    ),
    UriCase(
        "urltest_174",
        "GET \\.\\./ HTTP/1.1\r\n\r\n",
        method = "GET", path = "\\.\\./", version = 1,
        headers = listOf(),
    ),
    UriCase(
        "urltest_175",
        "GET :a@example.net HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = ":a@example.net", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_176",
        "GET %NBD HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "%NBD", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_177",
        "GET %1G HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "%1G", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_178",
        "GET /relative_import.html HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
        method = "GET", path = "/relative_import.html", version = 1,
        headers = listOf("Host" to "127.0.0.1"),
    ),
    UriCase(
        "urltest_179",
        "GET /?foo=%7B%22abc%22 HTTP/1.1\r\nHost: facebook.com\r\n\r\n",
        method = "GET", path = "/?foo=%7B%22abc%22", version = 1,
        headers = listOf("Host" to "facebook.com"),
    ),
    UriCase(
        "urltest_180",
        "GET /jqueryui@1.2.3 HTTP/1.1\r\nHost: localhost\r\n\r\n",
        method = "GET", path = "/jqueryui@1.2.3", version = 1,
        headers = listOf("Host" to "localhost"),
    ),
    UriCase(
        "urltest_181",
        "GET /path?query HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/path?query", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_182",
        "GET /foo/bar?a=b&c=d HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar?a=b&c=d", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_183",
        "GET /foo/bar??a=b&c=d HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar??a=b&c=d", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_184",
        "GET /foo/bar HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_185",
        "GET /baz?qux HTTP/1.1\r\nHost: foo.bar\r\n\r\n",
        method = "GET", path = "/baz?qux", version = 1,
        headers = listOf("Host" to "foo.bar"),
    ),
    UriCase(
        "urltest_186",
        "GET /baz?qux HTTP/1.1\r\nHost: foo.bar\r\n\r\n",
        method = "GET", path = "/baz?qux", version = 1,
        headers = listOf("Host" to "foo.bar"),
    ),
    UriCase(
        "urltest_187",
        "GET /baz?qux HTTP/1.1\r\nHost: foo.bar\r\n\r\n",
        method = "GET", path = "/baz?qux", version = 1,
        headers = listOf("Host" to "foo.bar"),
    ),
    UriCase(
        "urltest_188",
        "GET /baz?qux HTTP/1.1\r\nHost: foo.bar\r\n\r\n",
        method = "GET", path = "/baz?qux", version = 1,
        headers = listOf("Host" to "foo.bar"),
    ),
    UriCase(
        "urltest_189",
        "GET /baz?qux HTTP/1.1\r\nHost: foo.bar\r\n\r\n",
        method = "GET", path = "/baz?qux", version = 1,
        headers = listOf("Host" to "foo.bar"),
    ),
    UriCase(
        "urltest_190",
        "GET /C%3A/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C%3A/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_191",
        "GET /C%7C/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C%7C/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_192",
        "GET /C:/Users/Domenic/Dropbox/GitHub/tmpvar/jsdom/test/level2/html/files/pix/submit.gif HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/Users/Domenic/Dropbox/GitHub/tmpvar/jsdom/test/level2/html/files/pix/submit.gif", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_193",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_194",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_195",
        "GET /d: HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/d:", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_196",
        "GET /d:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/d:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_197",
        "GET /test?test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_198",
        "GET /test?test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_199",
        "GET /test?x HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?x", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_200",
        "GET /test?x HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?x", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_201",
        "GET /test?test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_202",
        "GET /test?test HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test?test", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_203",
        "GET /?fox HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/?fox", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_204",
        "GET /localhost//cat HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/localhost//cat", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_205",
        "GET /localhost//cat HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/localhost//cat", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_206",
        "GET /mouse HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/mouse", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_207",
        "GET /pig HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pig", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_208",
        "GET /pig HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pig", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_209",
        "GET /pig HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/pig", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_210",
        "GET /localhost//pig HTTP/1.1\r\nHost: lion\r\n\r\n",
        method = "GET", path = "/localhost//pig", version = 1,
        headers = listOf("Host" to "lion"),
    ),
    UriCase(
        "urltest_211",
        "GET /rooibos HTTP/1.1\r\nHost: tea\r\n\r\n",
        method = "GET", path = "/rooibos", version = 1,
        headers = listOf("Host" to "tea"),
    ),
    UriCase(
        "urltest_212",
        "GET /?chai HTTP/1.1\r\nHost: tea\r\n\r\n",
        method = "GET", path = "/?chai", version = 1,
        headers = listOf("Host" to "tea"),
    ),
    UriCase(
        "urltest_213",
        "GET /C: HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_214",
        "GET /C: HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_215",
        "GET /C: HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_216",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_217",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_218",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_219",
        "GET /dir/C HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/dir/C", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_220",
        "GET /dir/C|a HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/dir/C|a", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_221",
        "GET /c:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_222",
        "GET /c:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_223",
        "GET /c:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_224",
        "GET /c:/foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/c:/foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_225",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_226",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_227",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_228",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_229",
        "GET /C:/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/C:/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_230",
        "GET /?q=v HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/?q=v", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_231",
        "GET ?x HTTP/1.1\r\nHost: %C3%B1\r\n\r\n",
        method = "GET", path = "?x", version = 1,
        headers = listOf("Host" to "%C3%B1"),
    ),
    UriCase(
        "urltest_232",
        "GET ?x HTTP/1.1\r\nHost: %C3%B1\r\n\r\n",
        method = "GET", path = "?x", version = 1,
        headers = listOf("Host" to "%C3%B1"),
    ),
    UriCase(
        "urltest_233",
        "GET // HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "//", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_234",
        "GET //x/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "//x/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_235",
        "GET /someconfig;mode=netascii HTTP/1.1\r\nHost: foobar.com\r\n\r\n",
        method = "GET", path = "/someconfig;mode=netascii", version = 1,
        headers = listOf("Host" to "foobar.com"),
    ),
    UriCase(
        "urltest_236",
        "GET /Index.ut2 HTTP/1.1\r\nHost: 10.10.10.10\r\n\r\n",
        method = "GET", path = "/Index.ut2", version = 1,
        headers = listOf("Host" to "10.10.10.10"),
    ),
    UriCase(
        "urltest_237",
        "GET /0?baz=bam&qux=baz HTTP/1.1\r\nHost: somehost\r\n\r\n",
        method = "GET", path = "/0?baz=bam&qux=baz", version = 1,
        headers = listOf("Host" to "somehost"),
    ),
    UriCase(
        "urltest_238",
        "GET /sup HTTP/1.1\r\nHost: host\r\n\r\n",
        method = "GET", path = "/sup", version = 1,
        headers = listOf("Host" to "host"),
    ),
    UriCase(
        "urltest_239",
        "GET /foo/bar.git HTTP/1.1\r\nHost: github.com\r\n\r\n",
        method = "GET", path = "/foo/bar.git", version = 1,
        headers = listOf("Host" to "github.com"),
    ),
    UriCase(
        "urltest_240",
        "GET /channel?passwd HTTP/1.1\r\nHost: myserver.com\r\n\r\n",
        method = "GET", path = "/channel?passwd", version = 1,
        headers = listOf("Host" to "myserver.com"),
    ),
    UriCase(
        "urltest_241",
        "GET /foo.bar.org?type=TXT HTTP/1.1\r\nHost: fw.example.org\r\n\r\n",
        method = "GET", path = "/foo.bar.org?type=TXT", version = 1,
        headers = listOf("Host" to "fw.example.org"),
    ),
    UriCase(
        "urltest_242",
        "GET /ou=People,o=JNDITutorial HTTP/1.1\r\nHost: localhost\r\n\r\n",
        method = "GET", path = "/ou=People,o=JNDITutorial", version = 1,
        headers = listOf("Host" to "localhost"),
    ),
    UriCase(
        "urltest_243",
        "GET /foo/bar HTTP/1.1\r\nHost: github.com\r\n\r\n",
        method = "GET", path = "/foo/bar", version = 1,
        headers = listOf("Host" to "github.com"),
    ),
    UriCase(
        "urltest_244",
        "GET ietf:rfc:2648 HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "ietf:rfc:2648", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_245",
        "GET joe@example.org,2001:foo/bar HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "joe@example.org,2001:foo/bar", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_246",
        "GET /path HTTP/1.1\r\nHost: H%4fSt\r\n\r\n",
        method = "GET", path = "/path", version = 1,
        headers = listOf("Host" to "H%4fSt"),
    ),
    UriCase(
        "urltest_247",
        "GET https://example.com:443/ HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "https://example.com:443/", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_248",
        "GET d3958f5c-0777-0845-9dcf-2cb28783acaf HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "d3958f5c-0777-0845-9dcf-2cb28783acaf", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_249",
        "GET /test?%22 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%22", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_250",
        "GET /test HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_251",
        "GET /test?%3C HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%3C", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_252",
        "GET /test?%3E HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%3E", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_253",
        "GET /test?%E2%8C%A3 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%E2%8C%A3", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_254",
        "GET /test?%23%23 HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%23%23", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_255",
        "GET /test?%GH HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?%GH", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_256",
        "GET /test?a HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?a", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_257",
        "GET /test?a HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?a", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_258",
        "GET /test-a-colon-slash.html HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test-a-colon-slash.html", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_259",
        "GET /test-a-colon-slash-slash.html HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test-a-colon-slash-slash.html", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_260",
        "GET /test-a-colon-slash-b.html HTTP/1.1\r\nHost: \r\n\r\n",
        method = "GET", path = "/test-a-colon-slash-b.html", version = 1,
        headers = listOf("Host" to ""),
    ),
    UriCase(
        "urltest_261",
        "GET /test-a-colon-slash-slash-b.html HTTP/1.1\r\nHost: b\r\n\r\n",
        method = "GET", path = "/test-a-colon-slash-slash-b.html", version = 1,
        headers = listOf("Host" to "b"),
    ),
    UriCase(
        "urltest_262",
        "GET /test?a HTTP/1.1\r\nHost: example.org\r\n\r\n",
        method = "GET", path = "/test?a", version = 1,
        headers = listOf("Host" to "example.org"),
    ),
    UriCase(
        "urltest_nvidia",
        "GET /nvidia_web_services/controller.gfeclientcontent.php/com.nvidia.services.GFEClientContent.getShieldReady/{\"gcV\":\"2.2.2.0\",\"dID\":\"1341\",\"osC\":\"6.20\",\"is6\":\"1\",\"lg\":\"1033\",\"GFPV\":\"389.08\",\"isO\":\"1\",\"sM\":\"16777216\"} HTTP/1.0\r\nHost: gfwsl.geforce.com\r\n\r\n",
        method = "GET", path = "/nvidia_web_services/controller.gfeclientcontent.php/com.nvidia.services.GFEClientContent.getShieldReady/{\"gcV\":\"2.2.2.0\",\"dID\":\"1341\",\"osC\":\"6.20\",\"is6\":\"1\",\"lg\":\"1033\",\"GFPV\":\"389.08\",\"isO\":\"1\",\"sM\":\"16777216\"}", version = 0,
        headers = listOf("Host" to "gfwsl.geforce.com"),
    ),
)
